- .changeset/rare-poems-pay.md
- .changeset/wicked-candles-listen.md
- packages/colors/CHANGELOG.md
- packages/colors/package.json
- packages/colors/src/colors.ts
- 관련 쓰레드: https://sopt-makers.slack.com/archives/C041KKFNW57/p1694532951352509
> feat: makers color 1.0.0 추가

- packages/colors/CHANGELOG.md
- packages/colors/package.json
- packages/colors/src/colors.ts
> feat(colors): alpha 컬러 추가

- apps/docs/src/App.tsx
- apps/docs/src/stories/CheckBox.stories.tsx
- apps/web/app/page.tsx
- packages/ui/CheckBox/index.tsx
- packages/ui/CheckBox/style.css.ts
main을 pull 땡겨오면서 main의 내용이 원활하게 안 받아지는 이슈가 있어서... 다시 클론을 받게 되었습니다..! 아래의 PR는 코드리뷰 확인되는대로 close하겠습니다!
https://github.com/sopt-makers/makers-frontend/assets/76681519/0a5d83e6-8ec9-498d-8bd5-b92552c6b799
- 스토리북에는 문제없이 잘 뜨는데, vscode에는 다음과 같은 오류가 뜹니다.. 찾아보니, @types/react의 버전 오류라고 하더라고요,,,! 혹시 다른 분들은 이런 문제 없으신지요!
> feat: 체크박스 구현

- apps/docs/src/stories/Dialog.stories.tsx
- packages/ui/Dialog/DialogComponent.tsx
- packages/ui/Dialog/components/index.tsx
- packages/ui/Dialog/components/style.css.ts
- packages/ui/Dialog/index.tsx
- packages/ui/Dialog/style.css.ts
- packages/ui/Dialog/types.ts
- packages/ui/cssVariables.ts
- 다이얼로그에 애니메이션을 추가해주었습니다!
- 불필요하게 device를 prop으로 넘겨주고받는 부분을 없앴습니다! 완전한 반응형으로 구현하려고 했어요!
> chore: 다이얼로그 추가 작업

- apps/web/app/ToastTemp.tsx
- apps/web/app/globals.css
- apps/web/app/page.tsx
- packages/ui/package.json
- packages/ui/rollup.config.js
- packages/ui/tsconfig.json
- yarn.lock
- close #51
- rollup 설정 코드 정리
- 앱에 있는 Test 컴포넌트 관련 스토리랑 코드 제거하였습니다.
> chore(bundler): 코드 정리

- apps/docs/src/stories/Callout.stories.tsx
- packages/ui/Callout/Callout.tsx
- packages/ui/Callout/constants.ts
- packages/ui/Callout/index.tsx
- packages/ui/Callout/style.css.ts
- packages/ui/Callout/types.ts
- packages/ui/index.ts
- closes #92
**[ 옵션 ]**
- 타입 : danger, information, warning
- 아이콘 유무
- 버튼 유무
```tsx
interface CalloutProps {
content: string;
type: CalloutType;
hasIcon?: boolean;
buttonLabel?: string;
onClick?: () => void;
}
```
```tsx
export type CalloutType = "danger" | "information" | "warning";
```
```tsx
export default function Component() {  
const text = "Facebook 정책이 변경되어, ~ 부탁드려요.";
const handleClick = () => {
console.log("테스트!");
}
return (
<Callout
content={text}
type="information"
hasIcon
buttonLabel="소셜 계정 재설정하기"
onClick={handleClick}
/>
);
}
```
---
**스타일 오버라이딩을 허용해야 할까요?**
저는 디자인시스템이 있는 한 스타일 오버라이팅을 허용하지 않는 것이 맞다고 생각했는데, 이전 작업물들을 보니 허용한 것도 있고 안한 것도 있더라고요! 그래서 고민입니다만, 개인적으로는 Callout은 더더욱 배리를 줄 필요가 없는 컴포넌트라고 생각합니다.
---
Callout 컴포넌트는 다른 컴포넌트들에 비해 자유도가 굉장히 적은 친구입니다. 
모든 옵션(배경색, 테두리색, 버튼색, 아이콘 …
> feat(Callout) : Callout 컴포넌트 개발

- .changeset/two-mails-sin.md
- packages/ui/Input/Select.tsx
- buttonRef 추가로 드롭다운의 현재 상태 추적.
- 정상적인 토글 가능하도록 컨트롤
- formatting
> [FIX] Input/Select 컴포넌트의 드롭다운이 정상적으로 토글되지 않는 문제 수정.

- .changeset/big-bugs-camp.md
- .changeset/strong-pans-exercise.md
- packages/ui/Control/Toggle.tsx
- packages/ui/Control/style.css.ts
Toggle 컴포넌트의 접근성 및 타입을 추가합니다.
1. hover 시 cursor: pointer 속성 적용.
2. radix ui의 SwitchProp을 상속받아 해당하는 Prop을 상속받도록 수정.
> feat(Toggle): Toggle 컴포넌트가  SwitchProps을 확장하도록 수정

- .changeset/smart-mugs-invent.md
- packages/ui/Control/Radio.tsx
- Radio 컴포넌트에서 label이 정상적으로 입력되지 않던 문제를 수정합니다.
> fix(Radio): label 입력이 정상적으로 되지 않던 문제 수정

- .changeset/twenty-tables-rhyme.md
- packages/ui/scripts/buildCssModules.js
-  buildCssModules 내 script를 수정해 올바른 파일명으로 반응형을 지원할 수 있도록 합니다. 
> fix(ui): buildCssModules 내 script 수정

- .github/workflows/vitest.yml
Github Action을 통해 테스트 자동화 workflow를 작성하였어요.
🐢 천천히 : 급하지 않습니다.
> feat: 테스트를 자동화합니다.

- .changeset/eighty-planets-film.md
- packages/ui/Button/test/Button.test.tsx
Button 컴포넌트의 기본적인 동작을 검증하기 위한 유닛 테스트 코드를 작성했어요.
다음과 같은 case에 대한 테스트 코드를 작성했어요.
- Button 컴포넌트가 스크린에 정상적으로 렌더링되는지 확인
- 버튼을 클릭했을 때 onClick 이벤트 핸들러가 정상적으로 호출되는지 확인
- disabled 상태에서 버튼을 클릭했을 때 onClick 이벤트 핸들러가 호출되지 않는지 확인
UI에 대한 검증사항은 Storybook으로 충분하다고 생각해서 디자인 관련 variant prop이 정상적으로 적용되는지에 대한 테스트는 추가하지 않았어요.
++ vitest lint error 관련해서 찾아보는 중이에요. 원인 확인되는 대로 말씀드릴게요!
https://sopt-makers.slack.com/lists/T040QGZF77H/F07LCJ586TS?record_id=Rec07LCJ58NKS
> feat(Button): 유닛 테스트 코드를 작성합니다.

- .changeset/witty-cougars-breathe.md
- apps/docs/package.json
- packages/ui/package.json
- pnpm-lock.yaml
`color` 패키지의 버전 업데이트가 `ui` 패키지에 반영되지 않아서 이를 업데이트했어요.
> feat: ui 패키지 의존성을 업데이트합니다.

- .changeset/warm-hotels-march.md
- packages/ui/Tag/Tag.tsx
- packages/ui/Tag/index.tsx
- packages/ui/index.ts
- Tag 컴포넌트에 Div attr을 확장하고, ref를 추가합니다.
- [Slack](https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1730560366400109)
> fix(ui): Extend HTMLDivElement in Tag Component

- .changeset/chatty-plants-shave.md
- packages/ui/FieldBox/components/ErrorMessage.tsx
- packages/ui/Input/TextArea.tsx
> fix(ui): Textarea maxLength 초과시 error 뜨도록 변경

- .changeset/cold-owls-rule.md
- packages/ui/Tag/Tag.tsx
> feat(ui) Tag 컴포넌트에 ...restProps를 추가합니다.

- packages/ui/Input/Select.tsx
- packages/ui/Input/style.css.ts
> fix(ui): Select에 createPortal 적용

- .changeset/five-hornets-listen.md
> add changeset

- .changeset/calm-dolphins-shave.md
- packages/ui/Chip/style.css.ts
disabled 속성에 `pointer-events: none` 을 적용했어요
> fix(ui): Chip에 disabled 스타일 적용

- .changeset/thick-bikes-cough.md
- packages/ui/Button/style.css.ts
> fix(Button): disabled 상태일 경우 `cursor: not-allowed` 스타일 추가

- .changeset/few-goats-give.md
- packages/ui/Input/Select.tsx
- packages/ui/Input/style.css.ts
- 화면에 스크롤이 있는 경우, SelectMenu의 렌더링 위치 오류를 수정했습니다
- 화면 하단에 여유공간이 없는 경우, SelectTrigger 상단에 렌더링되도록 수정했습니다
> fix(ui) Select Menu 렌더링 위치 수정

- .changeset/shaggy-pigs-look.md
- packages/ui/Input/style.css.ts
> style(ui): Add align-items

- .github/CODEOWNERS
- README.md
> docs: Code owner 추가

- .changeset/five-dingos-bake.md
- .changeset/khaki-planes-reflect.md
- apps/docs/src/App.tsx
- apps/docs/src/stories/SelectV2WithTriggerContent.stories.tsx
- packages/ui/Input/Select.tsx
- packages/ui/Input/style.css.ts
1. 기존에 존재하던 SelectV2 컴포넌트에 다중선택 기능 추가하였습니다. 
2. Multiple 에 true 를 주입하면 됩니다.
3. 복수 선택 시 옆에 숫자가 뜨도록 구현이 되어 있습니다. (크루 sp 디자인 반영) 
4. 스토리북을 작성하였습니다. 작성하면서 추가 부연 설명을 채워 넣어두었습니다.  
5. app.tsx 에 테스트하며 진행하였습니다. 
<br />
https://github.com/user-attachments/assets/58a54fec-29c3-4342-b86b-256f4b31d452
https://github.com/user-attachments/assets/484a3737-295c-4490-af6f-4caf83994368
<br />
<br />
https://github.com/user-attachments/assets/5a98cd04-4ebd-4f74-8078-8ede1dc2f3c2
https://github.com/user-attachments/assets/c811dd4b-6d05-44a1-86d7-0c2290d33e2e
> feat(ui): SelectV2 컴포넌트에 다중선택 기능 추가
