- .changeset/odd-snakes-ring.md
- package.json
- packages/colors/CHANGELOG.md
- packages/colors/package.json
- packages/colors/src/colors.ts
- close: #7 
gray950이 추가되고, gray900의 값이 변경됩니다. ([피그마](https://www.figma.com/file/ZuAGH1zZDxduHsjCZm8kfH/%5B%EC%9D%B4%EA%B2%8C%EC%B5%9C%EC%A2%85%5D-Makers-design-system?type=design&node-id=504%3A418&mode=design&t=9sVhsmi7gK0aayH9-1))
> feat(colors): grayscale color 수정(2.1.0)

- packages/ui/CheckBox/style.css.ts
- packages/ui/Dialog/DialogComponent.tsx
- packages/ui/Dialog/DialogProvider.tsx
- packages/ui/Dialog/components/index.tsx
- packages/ui/Dialog/components/style.css.ts
- packages/ui/Dialog/index.tsx
- packages/ui/Dialog/style.css.ts
- packages/ui/Dialog/types.ts
- packages/ui/cssVariables.ts
- 기존 모달을 살펴보면 Footer가 없거나 하는 여러가지 경우의 수들이 있어서, descripiton에 직접 적용했던 margin bottom을 없애고, 대신 이 margin bottom을 고정 다이얼로그인 DialogComponent에 적용했어요. 
- 반응형을 추가했어요.
- 넥제에서 다이얼로그를 가져오면 하이드레이션 에러가 날 수 있습니다. 다이얼로그 컴포넌트를 직접 가져오면 ssr:false처리해주면 되지만, useDialog를 사용하면, 컴포넌트가 아니기 때문에 isMount가 true일 때 Provider가 띄워지도록 했습니다.
> feat: 다이얼로그 디테일 수정

- packages/fonts/src/fonts.ts
- packages/ui/theme.css.ts
- 폰트 객체로도 사용할 수 있도록 변경했는데, 이 방법이 괜찮을지 봐주시면 감사하겠습니다!!
- fonts를 fontsString으로 변경하였습니다! 혹시나 fonts를 사용하고 있을 레포를 위해서, 네이밍을 그대로 두었는데, fontObjects와의 구분을 위해서 네이밍을 변경하였어요! 만일 각자의 프로젝트에서 폰트 버전을 업그레이드한다면, 이 부분 꼭 챙겨주세용!
- 테스트 브랜치 파서, fontsString도 잘 적용되는지 확인 완료했습니다!
바닐라 익스트랙 환경에서는 다음과 같이 사용하시면 됩니다!
```
export const checkBoxLabel = styleVariants({
small: [
{
marginLeft: '8px',
},
theme.fontsObject.BODY_14_R,
],
large: [
{
marginLeft: '10px',
},
theme.fontsObject.BODY_16_R,
],
});
```
> refactor(fonts): 폰트 객체 형태 추가

- .changeset/quick-balloons-impress.md
- packages/ui/package.json
의존성 문제를 일으키는 `radix-dialog` 패키지가 프로덕션 빌드에 포함되도록 `devDependency`에서 `dependency`로 이동시킵니다.
> chore : radix-dialog devDependency에서 dependency로 이동

- .changeset/beige-roses-sip.md
- packages/ui/Input/Select.tsx
- defaultValue 사용 시 발생하는 오류를 없애기 위해 타입을 Option<T>로 변경합니다.
> fix(Select): defaultValue type Option<T>로 수정

- packages/eslint-config-custom/package.json
- packages/eslint-config-custom/react-internal.js
- packages/ui/.eslintrc.js
- packages/ui/Dialog/types.ts
- turbo.json
- yarn.lock
`release` 워크플로우에서 lint 스크립트 동작 과정에서 문제가 발생했어요.
원인은 vitest lint 세팅을 하고자 `react-internal.js`에 추가했던 부분 때문이었어요.
```js
extends: [
'@vercel/style-guide/eslint/browser',
'@vercel/style-guide/eslint/typescript',
'@vercel/style-guide/eslint/react',
// 새로 추가한 부분
'@vercel/style-guide/eslint/vitest,
].map(require.resolve),
```
패키지 코드에는 분명히 `vitest.js`가 존재했는데, 알고보니 저희 패키지에 설치된 `@vercel/style-guide`의 버전은 `5.0.0`이었고, Vitest eslint rule이 릴리즈된 버전은 `6.0.0` 버전이어서 오류가 발생했던 것이었어요.
그래서 latest 버전으로 업그레이드를 시도했는데, 문제가 많이 발생했어요.
latest 버전으로 업그레이드하게 되면 업그레이드한 패키지가 의존하는 vite 버전과 기존에 설치된 패키지가 요구하는 vite 버전에 충돌이 발생하게 돼요. 
lock파일 임의 변경도 금지되어 있어 여러모로 의존성 충돌을 해결하기 어려운 상황이라 `vitest`가 사용되는 `ui` 패키지 내부의 `eslint` 파일에서 직접 rule을 세팅해주기로 했어요.
4달 전 `eslint-plugin-vitest`라는 플러그인이 개발되어서 이걸 사용해서 lint 세팅을 해주었어요.
```js
// …
```
> fix(ui): vitest lint 세팅 오류 수정

- .github/workflows/release.yml
- package.json
`pnpm`으로 마이그레이션하면서 `release` workflow가 정상 동작하지 않았어요.
알아보니  `actions/setup-node` 액션을 사용하면 `Node.js`와 함께 `yarn`이 자동으로 설치되지만, pnpm은 그렇지 않다고 해요.
그래서 `pnpm/action-setup@v2` 액션을 추가하여 workflow에서 pnpm을 명시적으로 설치하고 사용할 수 있게 했어요.
그 결과 `release` workflow가 정상 동작하는 것을 확인했어요.
++ 추가 작업
`pnpm`으로 마이그레이션하면서 workspace를 `pnpm-workspace.yaml`이라는 별도의 파일에서 관리하게 되었는데, 아직 package.json에도 workspace 필드가 남아있어서 제거해주었습니다!
> fix: release workflow에 pnpm setup action 추가

- .changeset/tame-boxes-tickle.md
- packages/icons/package.json
- pnpm-lock.yaml
`icons` 패키지 빌드 오류 해결을 위해 `icons` 패키지에 `@types/react` 패키지를 추가했어요.
분명 로컬에선 빌드가 잘 되는데... 일단 존재해야 하는 패키지인 것은 맞고 로컬과 Github Action의 환경이 달라서 생긴 문제라고 추측을 하고 있어요. 자세한 이유는 더 알아볼 예정입니다!
++ 이번 수정은 patch로 올리면 될까요??
https://sopt-makers.slack.com/archives/C07L351P3JN/p1726231288746579
> fix: icons 패키지 빌드 오류 해결

- .changeset/spicy-ducks-beam.md
- packages/ui/Input/Select.tsx
- packages/ui/Input/deprecated/Select.tsx
- packages/ui/Input/index.tsx
- packages/ui/Input/style.css.ts
- packages/ui/index.ts
radix-ui의 컴포넌트 구성 방식을 참고하여 Select 컴포넌트를 리팩토링 했어요.
https://github.com/radix-ui/themes/blob/main/packages/radix-ui-themes/src/components/dropdown-menu.tsx
변경된 Select의 구성은 다음과 같아요
- Select.Root (하위 서브컴포넌트들에게 context를 내려줌)
- Select.Trigger (Select.Menu를 열수있는 Trigger)
- Select.TriggerContent (Select.Trigger의 미리 정의된 UI)
- Select.Menu (드롭다운을 감싸는 UI)
- Select.MenuItem (드롭다운 요소 하나의 UI)
> 기존의 Select 컴포넌트는 버튼 / 하단 dropdown이 하나의 컴포넌트로 이루어져 있어서 원하는 부분만 사용하기 어려웠어요.
> 그래서 합성컴포넌트 방식으로, 각 필요한 요소를 조합해서 사용할 수 있도록 했어요.
> 기존의 컴포넌트는 dropdown에 쓰일 데이터인 options를 prop으로 받고있었어요, 이 prop은 삭제 후 사용자가 직접 map과 같은 함수를 사용하여 dropdown의 요소들을 렌더링할 수있게 했고, 이 외의 동작은 동일하게 구성했어요.  - `Menu / MenuItem 으로 드롭다운 분리`
---
Select.Root에서 사용자는 prop으로 데이터를 전달해주게돼요. Select.Root는 전달받은 데이터를 바탕으로 정의된 함수 상태들을 자식요소에게 내려주는 역할을 해요. (`context`를 …
> feat(Select): Select를서브 컴포넌트로 분리하여 구성

- .changeset/fluffy-plants-double.md
- apps/docs/package.json
- apps/docs/src/stories/Select.stories.tsx
- apps/docs/src/stories/SelectV2NoTriggerContent.stories.tsx
- apps/docs/src/stories/SelectV2WithTriggerContent.stories.tsx
- pnpm-lock.yaml
https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1727270019264379?thread_ts=1727269906.082949&cid=C07AFHC6LDB
- 스토리북은 배포된 makers npm 패키지로 작성되어 있어, SelectV2를 사용하기 위해 `packege.json`에서 `makers/ui` 버전을 2.3.0으로 수정했어요.
- 기존 Select의 스토리북 경로를 deprecated로 이동 했어요.
- TriggerContent 사용 여부에 따라 두개로 케이스를 나누어 간단하게 스토리를 작성했습니다.
- 자세한 경로는 아래와 같습니다.
https://github.com/user-attachments/assets/cacb87d3-ed60-4d30-a82e-0540b18ea4bf
https://github.com/user-attachments/assets/b5131e08-1f88-4be6-bf17-9d3a4ff32028
> feat(Select): 서브 컴포넌트 사용 케이스를 나누어 스토리북 작성

- apps/docs/src/stories/Tab.stories.tsx
- packages/ui/Tab/test/Tab.test.tsx
close #155 
- tab 컴포넌트 unit 테스트를 작성했습니다.
- tab 컴포넌트가 제대로 렌더링 되는지 여부
- 각 tab을 클릭했을 때 onChange가 제대로 실행되는지 여부
- ui 관련된 부분은 크로마틱에서 확인 가능하여 제외했습니다.
- tab 스토리 파일에서, translator 관련한 부분 확인을 위해서 args에 translator를 추가했습니다. 
- translator는 tab의 실제 value를 대체할 텍스트를 나타내는 객체 입니다. ex) 실제 value는 `tab1`이고, 화면에 보여주고 싶은 text가 `탭1`이라면  `translator = { tab1: '탭1'}`와 같은 방식으로 작성하게 끔 코드가 구성되어있습니다.
https://sopt-makers.slack.com/lists/T040QGZF77H/F07LCJ586TS?record_id=Rec07LCJ58NKS
- 추후 pr 작성 시, 스토리북 변경사항이 있을 때 github action으로 chromatic 배포를 자동으로 하는 워크플로우가 있었으면 하는데, 어떻게 생각하시는지 궁금합니다!
- unit 테스트를 어느정도 작성 후에 test 코드도 ci 걸어두면 좋을것 같아요!
> feat(Tab): 유닛 테스트 코드를 작성합니다.

- .changeset/lucky-onions-hug.md
- packages/ui/Button/constants.ts
close #166 
MDS 요청에 따라서 일관성있게 Button의 size = 'md' 일때 text size를 `14px -> 16px` 로 변경했습니다.
- 변경 전 후
https://sopt-makers.slack.com/lists/T040QGZF77H/F07LCJ586TS?record_id=Rec07S0BXH1S4
간단한 반영사항이라서 편하게 확인해주시면 감사하겠습니다!
> refactor(Button): Button Medium 의 text size를 14px -> 16px로 변경합니다.

- .changeset/fluffy-dragons-shop.md
- apps/docs/package.json
- packages/ui/package.json
- pnpm-lock.yaml
- Storybook 패키지인 app/docs 패키지와 ui 패키지의 mds관련 패키지 의존성을 `workspace:^`로 변경합니다.
- 각 패키지의 의존성을 빌드된 패키지 내의 버전을 사용하도록 해 작업시에도 타 패키지에의 변경사항을 쉽게 반영해서 작업할 수 있도록 하고, 하나의 패키지의 버전이 변경됐을 때 자동으로 다른 패키지에도 변경된 버전이 적용되도록 해 유지보수가 쉽도록 하기 위함이에요.(링크 참조)
- https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1728585131331459
처음에 버전 명시만 바꿔줬는데 테스트를 실패하더라구요?
그래서 원인이 뭔지 파악해보니 `workspace:^` 설정은 말그대로 빌드가 완료된 패키지 내의 버전을 바라보기때문에 패키지가 빌드가 되지 않으면 패키지 자체를 찾지 못하는 문제가 있었어요
그래서 [해당 커밋](https://github.com/sopt-makers/makers-design-system/commit/5b22280ac89f12fa7245389538bc15f41c3562a2)에서 테스트 워크플로에 빌드 명령어를 추가했고, 무사히 테스트를 통과했어요.
> chore(ui, docs): 의존성 버전 workspace:^로 변경

- .changeset/serious-beers-swim.md
- packages/ui/Input/Select.tsx
- packages/ui/Input/style.css.ts
close #173 
```javascript
'::-webkit-scrollbar': {
width: '16px',
},
```
스크롤바 영역이 16px 만큼 차지하고 있어서 그랬습니다. 피그마 디자인 비교했을 때 관련해서 적용해야하는 사항이 없어서 삭제했습니다.
open 됐을 때 border가 아래 스타일 처럼 focus 선택자로 적용되고있었습니다. 해당 스타일은 trigger와 triggerContents로 컴포넌트가 나누어지면서 div태그인 triggerContents에 적용되는 스타일로 , div 태그에는 focus로 스타일을 받을 수 없기 때문에 일어난 현상이었습니다.
```javascript
export const select = style({
...theme.fontsObject.BODY_2_16_M,
'color': theme.colors.white,
'width': '160px',
'height': '48px',
'borderRadius': '10px',
'background': theme.colors.gray800,
'border': '1px solid transparent',
'padding': '11px 16px',
'display': 'flex',
'justifyContent': 'space-between',
'alignItems': 'center',
'gap': '12px',
'cursor': 'pointer',
'transition': 'border 0.2s',
// 해당 focus 스타일 삭제
':focus': {
border: `1px solid …
```
> refactor(Select): Select padding/border 명세와 상이한 부분 수정

- .changeset/sharp-boats-accept.md
- packages/ui/Input/style.css.ts
close #182 
#174 에 설명되어있듯이, `triggerContent`에 대한 `focus` style을 별도로 정의하게 되면서 `S.input` 스타일을 가져다가 사용하지 않게 되었고, `S.input`에 정의되어 있는 `border: 1px solid transparent`가 적용되지 않아서 border 유무에 따라 size가 변형되어 다른 요소가 밀리는 이슈가 발생했어요.
이를 해결하기 위해 별도로 정의한 `focus` style에 정의되어 있던 border를 box-shadow inset으로 변경하여 테두리가 생기더라도 요소의 size가 변형되지 않도록 하여 문제를 해결했어요.
- 논의하고 싶은 점
이렇게 되면 Select에서 Input의 공통 style을 참조하고 있지 않는데, Select를 Input으로 묶기보다 별도로 분리하는 건 어떤지에 대한 의견을 들어보고 싶어요!!
https://sopt-makers.slack.com/lists/T040QGZF77H/F07LCJ586TS?record_id=Rec07T75VU4T1
> fix(Select): border 유무에 따라 size가 변형되지 않도록 수정합니다.

- .changeset/popular-keys-share.md
- apps/docs/src/stories/Configure.mdx
- mds 링크트리를 추가한 Introduction 문서를 추가합니다.
> docs: Storybook Introduction 문서 추가

- .changeset/stale-rules-rhyme.md
- packages/ui/Button/style.css.ts
- Button 컴포넌트의 minWidth 속성에 max-content 속성을 추가합니다.
- https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1730575141856619?thread_ts=1728023641.439659&cid=C07AFHC6LDB
> fix(ui): Button 내 min-width 속성 추가

- .changeset/shiny-dogs-hope.md
- packages/ui/Input/TextArea.tsx
> fix(ui): Textarea maxLength 초과시 error 뜨도록 변경

- .changeset/good-flies-judge.md
- packages/colors/package.json
- packages/fonts/package.json
- packages/icons/package.json
- packages/ui/package.json
- pnpm-lock.yaml
- 전체 패키지를 배포하고 있던 기존의 번들을 dist 폴더와 variable.css만 배포하여 번들사이즈를 줄입니다.
- [슬랙](https://sopt-makers.slack.com/archives/C07L351P3JN/p1731497771462179)
> chore(all): Optimize packages

- .changeset/eight-donuts-act.md
- packages/ui/Input/TextArea.tsx
- https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1732297987583989?thread_ts=1731917913.722789&cid=C07AFHC6LDB
> fix(ui): TextArea 컴포넌트 forwardRef 추가, value prop optional로 변경.

- .changeset/pretty-eggs-teach.md
- apps/docs/src/App.tsx
- packages/ui/Input/TextArea.tsx
- MaxLength에서 발생하는 string.length가 value 가 undefined(e.g 빈 값일경우) 타입 추론을 하지 못하는 문제에서 발생합니다.
- 추후에 MaxLength의 경우에 FieldBox의 서브컴포넌트로 분리해 Textarea 자체에서는 MaxLength로 인한 타입 에러가 발생하지 않도록 방지해야 할 것 같습니다.
https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1732615027361309?thread_ts=1731917913.722789&cid=C07AFHC6LDB
> fix(ui): TextArea Value prop이 undefined일 경우 발생하는 타입 에러 수정

- .changeset/violet-ducks-juggle.md
- apps/docs/src/stories/FieldBox.stories.tsx
- packages/ui/FieldBox/FieldBox.tsx
- packages/ui/FieldBox/components/Label.tsx
- packages/ui/FieldBox/components/TopAddon.tsx
- packages/ui/FieldBox/components/index.ts
- packages/ui/FieldBox/style.css.ts
- packages/ui/Input/TextField.tsx
- FieldBox 컴포넌트에 TopAddon을 추가합니다.
- BottomAddon과 마찬가지로 leftAddon, rightAddon 추가가 가능하며, 기본적인 레이아웃 스타일이 제공됩니다.
-TextField에서 빈 BottomAddon이 레이아웃을 밀어내는 현상을 수정했습니다.
> feat(FieldBox): FieldBox 컴포넌트에 TopAddon을 추가합니다.

- .changeset/early-owls-protect.md
- packages/ui/Input/Select.tsx
- `SelectV2.TriggerContent`의 아이콘이 `ChevronDown`만으로 고정되어 있던 형태에서, ReactNode type의 `icon` 을 추가하여 다양한 아이콘을 추가할 수 있도록 수정합니다.
- https://sopt-makers.slack.com/archives/C07AFHC6LDB/p1734106307427189
> refactor(ui): SelectV2 TriggerContent 내 커스텀 Icon을 적용할 수 있도록 icon prop 추가.

- .changeset/short-hats-drop.md
- apps/docs/src/stories/Tag.stories.tsx
- packages/ui/Tag/Tag.tsx
- packages/ui/Tag/utils.ts
- Tag 컴포넌트에 커스텀 스타일을 적용할 수 있도록 className prop을 추가했습니다.
> feat(ui) Tag 컴포넌트에 className prop을 추가합니다.

- .changeset/tough-ligers-applaud.md
- packages/ui/Input/TextField.tsx
- TextField의 topAddon에 새로 변경된 FieldBox의 레이아웃이 적용되지 않았던 문제를 수정했어요.
- FieldBox의 TopAddon을 감싸줌으로써 온전한 FieldBox의 레이아웃을 가질 수 있도록 수정했습니다.
- https://sopt-makers.slack.com/archives/C042T8GEA0Y/p1736695443645079?thread_ts=1736683244.972439&cid=C042T8GEA0Y
> fix(ui): Add `<FieldBox.TopAddon />` in TextField's topAddon prop.

- .changeset/tender-cougars-deny.md
- packages/ui/Input/TextArea.tsx
- inputError의 focus상태일때 왼쪽의 스타일에서 오른쪽의 스타일이 되도록 수정하였습니다.
- inputError가 적용되었을 때 focus 스타일이 적용되지 않도록 `${!hasError && isFocused ? S.focus : ''}` 이와 같이 `!hasError `조건을 추가하였습니다.
- 메이커스 [디자인 시스템 피그마](https://www.figma.com/design/ZuAGH1zZDxduHsjCZm8kfH/%F0%9F%9A%80-makers-design-system?node-id=905-4571&p=f&t=2YEnW22U6AYqWrob-0)를 확인한 결과 error 상태일 때 active 스타일이 별도로 정의되어 있지 않아 해당 방식으로 수정했습니다..!
혹시 수정전의 스타일이 의도된 스타일이 맞다면 말씀 부탁드립니다!😀
- 기존에 플그팀에서는 inputError가 적용될 때 focus 스타일이 적용되지 않도록 하기 위해 mds가 아닌 별도의 컴포넌트를 만들어 사용하고 있었습니다. 이번 SP0 작업에서 해당 TextArea를 mds로 사용하기 위해 해당 부분을 수정했습니다.
> fix(TextArea): inputError가 적용되었을 때 focus 스타일이 적용되지 않도록 수정

- .cursor/rules/rules.mdc
- .vscode/settings.json
- .vscode/tasks.json
- package.json
- scripts/vscode.sh
1. 먼저 `cursor` 룰을 세팅했어요. 룰에 따라 커서와의 `chat` 혹은 프롬프트 기반 코드 추천을 커스터마이징하였어요. 프로젝트 구조와 코딩 컨벤션 등을 추가해주었어요.
2. vscode task를 추가해주었어요. 프로젝트 폴더를 킬때마다 Dev start라는 태스크가 실행돼요. 먼저 `ui` `color` `font` `icon` 은 `dist` 폴더를 기준으로 모듈이 호출되기 때문에 빌드되지 않은 상태라면 빌드 실행을 추가적으로 해주어야 했어요. 따라서 빌드된 결과물이 없다면 IDE를 킬 시에 자동으로 `build`가 진행될 수 있도록 하였어요. 또한 UI `vitest`를 진행하면서 테스트를 추가적으로 진행해주었어요.
🏃‍♂️ 천천히 : 급하지 않습니다.
> docs: cursor rule + vscode task 세팅

- apps/docs/src/stories/Tab.stories.tsx
- packages/ui/Tab/Tab.tsx
Tab의 translator 타입을 ` Record<T, string>`에서 ` Record<T, ReactNode>`로 변경하여 컴포넌트도 탭 내용에 추가될 수 있도록 수정했습니다.
[피그마 링크](https://www.figma.com/design/wQRUlMHjwFgWEvQs5tvEFO?node-id=127-14374&m=dev#1200255941)
> feat(ui): Tab 컴포넌트 타입 확장
